### ISSUE TITLE
Imágen para Manual Deployment(clase 4)

### ISSUE THREAD

**Issue by agustinpfs** [estebanrfp/git-guide#4]
Crear una imágen para el concepto de manual deployment 
LOCAL REPOSITORY (Development) -> REMOTE REPOSITORY (central) -> REMOTE REPOSITORY (production)

adjunto ejemplo
![screen_shot_2015-04-20_at_6 02 13_pm](https://cloud.githubusercontent.com/assets/9625917/7244044/cf275b48-e7ab-11e4-82f2-4ad66700ad74.png)

**Comment by andresxg** [comment]
f98794314deb84a6b557da3a535ec0a948bf739b
